### PR TITLE
Reservation delete confirmation

### LINKED ISSUE #279: Confirm delete booking
**User Story:**

As a user/restaurant owner, I want to confirm that I would like to permanently delete a booking so that I don't accidentally remove a reservation that I wasn't supposed to delete.

**Acceptance Criteria:**
- [ ] A new popup screen asking to confirm or cancel deletion of a booking appears
- [ ] Clicking on cancel does not remove the booking
- [ ] Clicking on confirm permanently deletes the booking
- [ ] This is handled on both the "Edit Booking" Popup dialog accessible from the Homepage and the Reservations screen

**Additional Context:**

### PR DESCRIPTION
**Pull request by mitchfaulcon**
## Link to Issue Number
Closes #279 

## Description
There is now checks to confirm the user wants to delete a reservation, both from the reservations screen and from the edit booking popup.

## Checklist
- [x] All feature request A/C have been met OR the bug has been fixed
- [ ] I ran all necessary tests and they pass
- [x] I rebased upstream/master onto my working branch before opening this PR
- [x] I have named my PR something sensible
- [x] I have included the issue number above
- [x] I have assigned at least two people to review my changes

### CODE REVIEW

**Comment by jhsi517** [comment]
Tried to delete the test reservation (ID: 80gyicblgk954awny), but it doesn't seem to work for both delete from reservation & edit booking.  

The other test reservation (ID: 1) seems to work fine.

Note: both these tests data are from the restaurant_db.sql (22nd Apr)

Could you please investigate.

**Comment by mitchfaulcon** [comment]
That's because that booking was made for 19/4/2020, which happens to be in the past so it returns an error that the date has passed. Ideally, we would want to delete them from the database after the booking date/time has passed (or something else completely - not sure what others would want), but that can be done in another issue & pr

**Comment by jhsi517** [comment]
I see. Thank you for the clarification :)

**Comment by jhsi517** [comment]
@gargi-bansal you may have accidentally clicked review instead of approve :)

**Comment by gargi-bansal** [comment]
> @gargi-bansal you may have accidentally clicked review instead of approve :)

@jhsi517 I helped write some of this code, so I don't think I should be the one approving it :)

**Pull request merged**
